#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-.env.hosted.local}"
umask 077

banner "RoboRecon hosted setup"

stage "Provider accounts and repository access"
say "We will deploy the existing GitHub repository to Vercel, connect Neon PostgreSQL, and use Razorpay Test Mode."
open_url "https://vercel.com/new"
open_url "https://console.neon.tech/app/projects"
open_url "https://dashboard.razorpay.com"
step "Sign in to Vercel and confirm the GitHub repository heykay-47/roborecon is available to import."
step "Sign in to Neon and Razorpay. You need permission to create a database and generate Razorpay API keys."
pause "When all three dashboards are ready, press Enter."

stage "Neon: pooled database URL"
say "The API uses a pooled Neon connection because it runs as a serverless function."
open_url "https://console.neon.tech/app/projects/new"
step "Create a Neon project, or select the project intended for this demo."
step "On the project dashboard click Connect, choose the branch, database, and role, enable Connection pooling, and copy the URL with -pooler in its hostname."
ask_secret DATABASE_URL "Paste the pooled DATABASE_URL:"
if [[ -z "$DATABASE_URL" ]]; then
  warn "DATABASE_URL is required; rerun the wizard after copying the pooled connection string."
  exit 1
fi
write_env DATABASE_URL "$DATABASE_URL"
note "This value is saved only in the ignored $ENV_FILE and must also be entered in the API Vercel project."

stage "Razorpay: Test Mode credentials"
say "Only Test Mode credentials are used. Test Mode does not move real money."
open_url "https://razorpay.com/docs/payments/dashboard/account-settings/api-keys/"
open_url "https://dashboard.razorpay.com"
step "Switch the Razorpay Dashboard to Test Mode. Go to Account & Settings → API Keys under Website and app settings, then choose Generate Key."
step "Copy the Key ID while it is visible."
ask RAZORPAY_KEY_ID "Paste the Test Mode Key ID:"
step "Copy the Key Secret when Razorpay shows it. Razorpay will not show the secret again after this screen."
ask_secret RAZORPAY_KEY_SECRET "Paste the Test Mode Key Secret:"
if [[ -z "$RAZORPAY_KEY_ID" || -z "$RAZORPAY_KEY_SECRET" ]]; then
  warn "Both Razorpay Test Mode values are required; rerun the wizard after generating the key."
  exit 1
fi
write_env RAZORPAY_KEY_ID "$RAZORPAY_KEY_ID"
write_env RAZORPAY_KEY_SECRET "$RAZORPAY_KEY_SECRET"
note "The secret is hidden while entering it and is saved only in the ignored $ENV_FILE."

stage "Vercel: deploy the API"
say "The API project must be deployed first so the Web project can use its public URL."
open_url "https://vercel.com/new"
step "Import heykay-47/roborecon. Set Root Directory to apps/api. Keep the API's existing vercel.json settings and use Vercel's detected FastAPI/Python framework preset."
step "In Environment Variables, add these Production values: DATABASE_URL, SERVERLESS=true, DEMO_MODE=true, RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET, and temporary CORS_ORIGINS=http://localhost:3000."
step "Paste the captured database and Razorpay values into Vercel. Select Preview too if you want branch preview deployments to work. Never use Live Mode keys."
if ! confirm "Have you deployed the API project and can see its successful deployment URL?"; then
  warn "The API deployment was not confirmed. Re-run this wizard when it is ready."
  exit 0
fi
step "Copy the API deployment URL without a trailing slash."
ask HOSTED_API_URL "Paste the public API URL:"
if [[ -z "$HOSTED_API_URL" ]]; then
  warn "The API URL is required for the Web deployment."
  exit 1
fi
write_env HOSTED_API_URL "$HOSTED_API_URL"

stage "Vercel: deploy the Web app"
say "The Web app will be built from apps/web and will call the API URL captured in the previous stage."
open_url "https://vercel.com/new"
step "Import heykay-47/roborecon as a second Vercel project. Set Root Directory to apps/web and use the Vite framework preset."
step "In Environment Variables, add Production VITE_API_URL with this value: $HOSTED_API_URL. Select Preview too if needed."
if ! confirm "Have you deployed the Web project and can see its successful deployment URL?"; then
  warn "The Web deployment was not confirmed. Re-run this wizard when it is ready."
  exit 0
fi
step "Copy the Web deployment URL without a trailing slash."
ask HOSTED_WEB_URL "Paste the public Web URL:"
if [[ -z "$HOSTED_WEB_URL" ]]; then
  warn "The Web URL is required to finish the CORS configuration."
  exit 1
fi
write_env HOSTED_WEB_URL "$HOSTED_WEB_URL"
write_env VITE_API_URL "$HOSTED_API_URL"

stage "Vercel: finalize API CORS"
say "The API must allow requests from the final Web deployment origin."
open_url "https://vercel.com/dashboard"
step "Select the API project, open Settings → Environment Variables, and edit Production CORS_ORIGINS."
step "Replace the temporary localhost value with $HOSTED_WEB_URL, without a trailing slash. Save the variable and redeploy the API."
write_env CORS_ORIGINS "$HOSTED_WEB_URL"
if ! confirm "Have you saved CORS_ORIGINS and completed the API redeployment?"; then
  warn "CORS is not confirmed. The Web app may be blocked by the browser until this is completed."
  exit 0
fi

stage "Hosted judge verification"
say "This final check confirms the public app, database-backed demo, and read-only Razorpay connector."
open_url "$HOSTED_WEB_URL"
open_url "$HOSTED_API_URL/health"
step "In the Web app, use Reset demo data, run reconciliation, and inspect Overview, Runs, Exceptions, Audit, and Copilot."
step "From a terminal, run: curl --fail --silent --show-error --request POST $HOSTED_API_URL/razorpay/sync"
step "Confirm the sync response contains a batchId and sourceCounts. Imported Razorpay data is source-only and does not receive seeded benchmark accuracy metrics."
pause "When the hosted judge flow is complete, press Enter."

finish
